In [2]:
from imblearn.over_sampling import SMOTE, ADASYN
import pandas as pd

In [3]:
data_raw=pd.read_csv(r"./data/raw_data.csv")
data_finished=data_raw[data_raw["Finished"]==True].reset_index(drop=True)
data_finished['Age']=data_finished['Age'].fillna(int(data_finished['Age'].mean()))
data_finished=data_finished.dropna()

In [4]:
data_finished

,Finished,Extraversion,Observant,Thinking,Judging,Age,Gender,education,Major,way of watching movies,...,factors,Action,Adventure,Animated,Comedy,Historical,Fantasy,Horror,Science fiction,Documentary
0,True,71,64,58,93,23.0,Male,master or above,engineering and techonology,on mobile devices at home or other places,...,"Actor/actress,director,genres",Strongly like,Strongly like,neither like nor dislike,like,Strongly dislike,like,neither like nor dislike,Strongly like,dislike
1,True,51,78,76,58,21.0,Male,master or above,engineering and techonology,Go to cinema or theatres,...,"Actor/actress,director,previews",like,dislike,dislike,neither like nor dislike,like,dislike,Strongly dislike,like,neither like nor dislike
2,True,57,63,33,39,21.0,Female,bachelor,science and math-related,on mobile devices at home or other places,...,"Actor/actress,previews,comments of other audience",dislike,like,Strongly like,like,Strongly dislike,Strongly like,like,like,like
3,True,83,16,65,51,23.0,Female,master or above,science and math-related,on mobile devices at home or other places,...,"Actor/actress,genres,comments of other audience",dislike,dislike,Strongly like,Strongly like,dislike,like,Strongly dislike,neither like nor dislike,neither like nor dislike
4,True,25,59,68,32,22.0,Male,bachelor,science and math-related,on mobile devices at home or other places,...,"genres,previews,comments of other audience",like,like,dislike,dislike,dislike,like,dislike,Strongly like,dislike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543,True,60,46,70,68,20.0,Male,bachelor,science and math-related,on mobile devices at home or other places,...,"Actor/actress,genres,previews",like,neither like nor dislike,dislike,like,neither like nor dislike,like,neither like nor dislike,Strongly like,like
544,True,90,35,47,32,26.0,Male,master or above,science and math-related,Go to cinema or theatres,...,"director,genres,comments of other audience",dislike,neither like nor dislike,like,dislike,dislike,like,neither like nor dislike,like,Strongly like
545,True,75,58,60,80,22.0,Female,bachelor,literature language and social sciences,on mobile devices at home or other places,...,"Actor/actress,previews,comments of other audience",neither like nor dislike,dislike,neither like nor dislike,like,like,like,Strongly dislike,neither like nor dislike,like
546,True,82,90,61,70,21.0,Male,master or above,engineering and techonology,on mobile devices at home or other places,...,"advertisements,previews,comments of other audi...",like,like,like,like,like,like,like,like,like
547,True,63,67,56,64,25.0,Female,master or above,science and math-related,on mobile devices at home or other places,...,"advertisements,previews,comments of other audi...",neither like nor dislike,neither like nor dislike,neither like nor dislike,neither like nor dislike,Strongly like,like,Strongly like,neither like nor dislike,neither like nor dislike

In [5]:
data_finished=data_finished.drop('Finished',axis=1)
#remove data including abnormal ages
data_finished=data_finished[data_finished['Age']>15]
data_finished=data_finished[data_finished['Age']<65]
data_finished=data_finished.reset_index(drop=True)
#remove data including abnormal mbti test results
data_finished=data_finished[data_finished['Extraversion']<100]
data_finished=data_finished[data_finished['Observant']<100]
data_finished=data_finished[data_finished['Thinking']<100]
data_finished=data_finished[data_finished['Judging']<100]

In [6]:
data_finished

,Extraversion,Observant,Thinking,Judging,Age,Gender,education,Major,way of watching movies,subscription,...,factors,Action,Adventure,Animated,Comedy,Historical,Fantasy,Horror,Science fiction,Documentary
0,71,64,58,93,23.0,Male,master or above,engineering and techonology,on mobile devices at home or other places,Yes,...,"Actor/actress,director,genres",Strongly like,Strongly like,neither like nor dislike,like,Strongly dislike,like,neither like nor dislike,Strongly like,dislike
1,51,78,76,58,21.0,Male,master or above,engineering and techonology,Go to cinema or theatres,Yes,...,"Actor/actress,director,previews",like,dislike,dislike,neither like nor dislike,like,dislike,Strongly dislike,like,neither like nor dislike
2,57,63,33,39,21.0,Female,bachelor,science and math-related,on mobile devices at home or other places,Somtimes,...,"Actor/actress,previews,comments of other audience",dislike,like,Strongly like,like,Strongly dislike,Strongly like,like,like,like
3,83,16,65,51,23.0,Female,master or above,science and math-related,on mobile devices at home or other places,Somtimes,...,"Actor/actress,genres,comments of other audience",dislike,dislike,Strongly like,Strongly like,dislike,like,Strongly dislike,neither like nor dislike,neither like nor dislike
4,25,59,68,32,22.0,Male,bachelor,science and math-related,on mobile devices at home or other places,Somtimes,...,"genres,previews,comments of other audience",like,like,dislike,dislike,dislike,like,dislike,Strongly like,dislike
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
538,60,46,70,68,20.0,Male,bachelor,science and math-related,on mobile devices at home or other places,Somtimes,...,"Actor/actress,genres,previews",like,neither like nor dislike,dislike,like,neither like nor dislike,like,neither like nor dislike,Strongly like,like
539,90,35,47,32,26.0,Male,master or above,science and math-related,Go to cinema or theatres,Yes,...,"director,genres,comments of other audience",dislike,neither like nor dislike,like,dislike,dislike,like,neither like nor dislike,like,Strongly like
540,75,58,60,80,22.0,Female,bachelor,literature language and social sciences,on mobile devices at home or other places,Somtimes,...,"Actor/actress,previews,comments of other audience",neither like nor dislike,dislike,neither like nor dislike,like,like,like,Strongly dislike,neither like nor dislike,like
541,82,90,61,70,21.0,Male,master or above,engineering and techonology,on mobile devices at home or other places,Yes,...,"advertisements,previews,comments of other audi...",like,like,like,like,like,like,like,like,like
542,63,67,56,64,25.0,Female,master or above,science and math-related,on mobile devices at home or other places,Somtimes,...,"advertisements,previews,comments of other audi...",neither like nor dislike,neither like nor dislike,neither like nor dislike,neither like nor dislike,Strongly like,like,Strongly like,neither like nor dislike,neither like nor dislike

In [7]:
data_y=data_finished[['Action','Adventure','Animated','Comedy','Historical','Fantasy','Horror','Science fiction','Documentary']]
data_x=data_finished.drop(columns=['Action','Adventure','Animated','Comedy','Historical','Fantasy','Horror','Science fiction','Documentary'],axis=1)

In [10]:
data=pd.read_csv(r'./data/data_clean_v2.csv')

In [11]:
data

,Extraversion,Observant,Thinking,Judging,Age,way of watching movies,Action,Adventure,Animated,Comedy,...,with_With friends,with_alone,with_with boyfriend/girlfriend,with_with family,Actor/actress,director,advertisements,genres,previews,comment
0,71,64,58,93,23.0,0,5,5,3,4,...,1,0,0,0,1.0,1.0,0.0,1.0,0.0,0.0
1,51,78,76,58,21.0,1,4,2,2,3,...,1,0,0,0,1.0,1.0,0.0,0.0,1.0,0.0
2,57,63,33,39,21.0,0,2,4,5,4,...,0,0,1,0,1.0,0.0,0.0,0.0,1.0,1.0
3,83,16,65,51,23.0,0,2,2,5,5,...,0,0,1,0,1.0,0.0,0.0,1.0,0.0,1.0
4,25,59,68,32,22.0,0,4,4,2,2,...,0,0,1,0,0.0,0.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,60,46,70,68,20.0,0,4,3,2,4,...,0,0,0,1,1.0,0.0,0.0,1.0,1.0,0.0
529,90,35,47,32,26.0,1,2,3,4,2,...,0,1,0,0,0.0,1.0,0.0,1.0,0.0,1.0
530,75,58,60,80,22.0,0,3,2,3,4,...,1,0,0,0,1.0,0.0,0.0,0.0,1.0,1.0
531,82,90,61,70,21.0,0,4,4,4,4,...,0,0,1,0,0.0,0.0,1.0,0.0,1.0,1.0
532,63,67,56,64,25.0,0,3,3,3,3,...,1,0,0,0,0.0,0.0,1.0,0.0,1.0,1.0

In [12]:
data_y=data[['Action','Adventure','Animated','Comedy','Historical','Fantasy','Horror','Science fiction','Documentary']]
data_x=data.drop(columns=['Action','Adventure','Animated','Comedy','Historical','Fantasy','Horror','Science fiction','Documentary'],axis=1)

In [13]:
x_resample, y_resample = SMOTE().fit_resample(data_x,data_y['Action'])

In [14]:
x_resample

,Extraversion,Observant,Thinking,Judging,Age,way of watching movies,Gender_Female,Gender_Male,Gender_Non-binary / third gender,Entertaining,...,with_With friends,with_alone,with_with boyfriend/girlfriend,with_with family,Actor/actress,director,advertisements,genres,previews,comment
0,71,64,58,93,23.000000,0,0,1,0,1.000000,...,1,0,0,0,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000
1,51,78,76,58,21.000000,1,0,1,0,1.000000,...,1,0,0,0,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
2,57,63,33,39,21.000000,0,1,0,0,1.000000,...,0,0,1,0,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000
3,83,16,65,51,23.000000,0,1,0,0,1.000000,...,0,0,1,0,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000
4,25,59,68,32,22.000000,0,0,1,0,0.000000,...,0,0,1,0,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1240,53,42,55,47,18.000000,0,0,0,0,0.780948,...,0,0,0,0,1.000000,1.000000,0.780948,0.219052,0.000000,0.000000
1241,52,44,54,48,18.000000,0,0,0,0,0.650963,...,0,0,0,0,1.000000,1.000000,0.650963,0.349037,0.000000,0.000000
1242,18,52,47,57,20.920591,1,0,0,0,0.079409,...,0,1,0,0,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000
1243,50,38,59,42,18.485357,0,1,0,0,1.000000,...,0,0,0,0,0.838214,0.838214,0.838214,0.161786,0.161786,0.161786
1244,67,42,51,50,19.535322,0,1,0,0,0.232339,...,0,0,0,0,1.000000,0.232339,0.232339,0.767661,0.767661,0.000000